### ISSUE TITLE
make error on ubuntu 18.04

### ISSUE THREAD

**Issue by braselectron** [Dakostu/MiniStocks#3] opened 2019-09-06 16:15 UTC
my system is:

Intel Core2Duo 6300 / 8GB
Ubuntu 18.04.3 LTS
4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

while trying to make the code, I get this output:

~/Downloads/MiniStocks-master/build$ make
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../StockTicker -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I../StockTicker -I. -o MainWindow.o ../StockTicker/dialogs/MainWindow.cpp
../StockTicker/dialogs/MainWindow.cpp: In constructor ‘MainWindow::MainWindow(QWidget*)’:
../StockTicker/dialogs/MainWindow.cpp:30:11: error: ‘class MainWindow’ has no member named ‘setWindowFlag’; did you mean ‘setWindowFlags’?
     this->setWindowFlag(Qt::FramelessWindowHint, true);
           ^~~~~~~~~~~~~
           setWindowFlags
Makefile:266: recipe for target 'MainWindow.o' failed

make: *** [MainWindow.o] Error 1

**Comment by alexmyczko** [comment] 2020-01-15 10:34
it builds just fine for me here with 18.04 and qt5, for some reason the Makefile picks qt4 for you

i've tried a master.tar.gz download from today

without a file with "AAPL" or any text inside /home/YOURUSERNAME/.ministocks/savedtickers
it segfaults

apart from that it starts, however it shows me

```
AAPL     0.00    (nan%)
```

**Comment by Dakostu** [comment] 2020-01-19 22:08
Wow.. I never got any notification from GitHub that an issue has been opened for this project. 
Sorry for the belated response.

@braselectron Have you tried recompilation with qt5?

@alexmyczko check out the new branch `file-not-found-fix` and check if the problem still persists with a non-existent file.
Also, the program uses stock data from the stooq.com API (because Yahoo Finance! killed off their API) which includes ticker names. So Apple for example, is https://stooq.pl/q/?s=aapl.us

**Comment by alexmyczko** [comment] 2020-01-20 07:18
@Dakostu indeed your hints make it work! that's great. thank you very much.

Debian/Ubuntu source packages if anyone wants to try:
http://phd-sid.ethz.ch/debian/ministocks/

**Comment by Dakostu** [comment] 2020-01-20 14:33
@alexmyczko Nice..... awesome 😮

Let's see whether it works now for @braselectron

**Comment by braselectron** [comment] 2020-01-20 21:38
Dear friends, 

Since I opened this many months ago, and I struggled with it a few days to make the process work, at the end I didn't continue because, as you must know, Ubuntu 18.04.3 does not come with qt5 installed for building things, so I did not continue with the effort.

I did install qt5-qmake but I need to install qt5 creator stuff to be able to compile, but since I do not want to "break" my system, I need to find a safe way to install qt5 dependencies and finally modify Makefile to give you a feedback.  If you have done this with success on your stable system please don't hesitate to share (the minimum install) how you did it for qt5, and how you kept the sanity of your system.

**Comment by alexmyczko** [comment] 2020-01-21 06:05
@dakostu, @braselectron I can confirm ministocks just works on 18.04 as well, here's a simple backport I made: 
http://phd-sid.ethz.ch/debian/ministocks/18.04/

**Comment by braselectron** [comment] 2020-01-22 22:03
Dear @alexmyczko I downloaded the deb on your link and it did work!  It took about 16 seconds before opening the the final widget window.   Did you compile it with qt4 or qt5 or did you change the Makefile ?  Please share how you got it to work ?   But I notice that is does not stop downloading.  It should have same kind of time setting to pause between attempts of fetching quotes.

**Comment by alexmyczko** [comment] 2020-01-23 16:20
> Dear @alexmyczko I downloaded the deb on your link and it did work! It took about 16 seconds before opening the the final widget window. Did you compile it with qt4 or qt5 

qt5

or did you change the Makefile ? Please share how you got it to work ?

no patches, see the same url into debian/rules

 But I notice that is does not stop downloading. It should have same kind of time setting to pause between attempts of fetching quotes.

**Comment by Dakostu** [comment] 2020-01-24 11:16
I'll close this issue since it seems to be resolved. Thank you all for your solutions and your patience ;)

Regarding ticker download timing: It's on my to-do list now!

**Closed as completed by Dakostu** 2020-01-24 11:16 UTC
